context:
  version: 0.1.0

package:
  name: prosemd-lsp
  version: ${{ version }}

source:
  url: https://github.com/kitten/prosemd-lsp/archive/v${{ version }}.tar.gz
  sha256: 456e89becc755f79b39bdbe87955964feebe26bb898b2a2022cd9ddd80c13990

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - prosemd-lsp --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: An experimental proofreading and linting language server for markdown files
  homepage: https://github.com/kitten/prosemd-lsp
  repository: https://github.com/kitten/prosemd-lsp

extra:
  recipe-maintainers:
    - danielnachun
